-- Phase 1 / task 1.2 - reference seed (DESIGN.md 7.1, 11.1; ARCHITECTURE.md 10.3; REQUIREMENTS.md 3.3).
-- GENERATED CONTENT: the role -> permission map below expands ARCHITECTURE 10.3; deviations are listed in docs/decisions.md.
-- Numbered V3_1 so it runs after the V3 schema and before the Phase 2 inventory schema (V4).

INSERT INTO permissions (code, module, description) VALUES
  ('USER_VIEW', 'IAM', 'View users'),
  ('USER_CREATE', 'IAM', 'Create users'),
  ('USER_UPDATE', 'IAM', 'Update users and assign roles'),
  ('USER_DELETE', 'IAM', 'Deactivate users (users are never deleted)'),
  ('ROLE_MANAGE', 'IAM', 'Manage roles and their permissions'),
  ('PERMISSION_MANAGE', 'IAM', 'Manage the permission catalogue'),
  ('SETTINGS_MANAGE', 'IAM', 'Change system settings'),
  ('AUDIT_VIEW', 'IAM', 'View and export the audit log'),
  ('MASTERDATA_MANAGE', 'MASTER_DATA', 'Manage materials and general master data'),
  ('MATERIAL_VIEW', 'MASTER_DATA', 'View materials'),
  ('SUPPLIER_MANAGE', 'MASTER_DATA', 'Manage suppliers'),
  ('CUSTOMER_MANAGE', 'MASTER_DATA', 'Manage customers'),
  ('WAREHOUSE_MANAGE', 'MASTER_DATA', 'Manage warehouses'),
  ('LOCATION_MANAGE', 'MASTER_DATA', 'Manage warehouse locations'),
  ('MACHINE_MANAGE', 'MASTER_DATA', 'Manage the machine master'),
  ('OPERATION_MANAGE', 'MASTER_DATA', 'Manage standard operations'),
  ('REJECTION_REASON_MANAGE', 'MASTER_DATA', 'Manage rejection reasons'),
  ('PRODUCT_VIEW', 'ENGINEERING', 'View spring products and specifications'),
  ('PRODUCT_CREATE', 'ENGINEERING', 'Create spring products'),
  ('PRODUCT_UPDATE', 'ENGINEERING', 'Update spring products and specifications'),
  ('DRAWING_MANAGE', 'ENGINEERING', 'Manage drawing numbers and revisions'),
  ('BOM_VIEW', 'ENGINEERING', 'View bills of material'),
  ('BOM_CREATE', 'ENGINEERING', 'Create bills of material'),
  ('BOM_UPDATE', 'ENGINEERING', 'Edit and revise bills of material'),
  ('BOM_REVIEW', 'ENGINEERING', 'Review bills of material (engineering review)'),
  ('BOM_APPROVE', 'ENGINEERING', 'Approve bills of material'),
  ('ROUTING_MANAGE', 'ENGINEERING', 'Define product routings'),
  ('INVENTORY_VIEW', 'INVENTORY', 'View stock, ledger and batches (warehouse-scoped)'),
  ('INVENTORY_VIEW_ALL', 'INVENTORY', 'View stock in all warehouses'),
  ('INVENTORY_RECEIVE', 'INVENTORY', 'Receive material against goods receipts'),
  ('INVENTORY_ISSUE', 'INVENTORY', 'Issue material'),
  ('INVENTORY_TRANSFER', 'INVENTORY', 'Transfer stock between locations and statuses'),
  ('INVENTORY_RETURN', 'INVENTORY', 'Record material returns'),
  ('INVENTORY_ADJUST', 'INVENTORY', 'Request stock adjustments'),
  ('ADJUST_REVIEW', 'INVENTORY', 'Review stock adjustments (supervisor step)'),
  ('ADJUST_APPROVE', 'INVENTORY', 'Approve stock adjustments below the Admin threshold'),
  ('ADJUST_APPROVE_ADMIN', 'INVENTORY', 'Approve stock adjustments above the Admin threshold'),
  ('STOCK_COUNT', 'INVENTORY', 'Perform stock counts'),
  ('VALUATION_VIEW', 'INVENTORY', 'View stock valuation'),
  ('PURCHASE_VIEW', 'PURCHASE', 'View purchase orders and receipts'),
  ('PURCHASE_CREATE', 'PURCHASE', 'Create and edit purchase orders'),
  ('PURCHASE_APPROVE', 'PURCHASE', 'Approve purchase orders'),
  ('REQUISITION_CREATE', 'PURCHASE', 'Create purchase requisitions'),
  ('PRODUCTION_VIEW', 'PRODUCTION', 'View all production orders'),
  ('PRODUCTION_CREATE', 'PRODUCTION', 'Create production orders'),
  ('PRODUCTION_UPDATE', 'PRODUCTION', 'Update production orders'),
  ('PRODUCTION_APPROVE', 'PRODUCTION', 'Approve production orders'),
  ('PRODUCTION_RELEASE', 'PRODUCTION', 'Release production orders'),
  ('PRODUCTION_SCHEDULE', 'PRODUCTION', 'Schedule production'),
  ('PRODUCTION_ASSIGN', 'PRODUCTION', 'Assign lines, machines, supervisors and operators'),
  ('PRODUCTION_EXECUTE', 'PRODUCTION', 'Execute assigned operations and record output'),
  ('PRODUCTION_CLOSE', 'PRODUCTION', 'Close completed production orders'),
  ('PRODUCTION_REOPEN', 'PRODUCTION', 'Reopen or edit completed production orders'),
  ('DOWNTIME_RECORD', 'PRODUCTION', 'Record machine downtime'),
  ('MATERIAL_REQUEST', 'PRODUCTION', 'Request additional material'),
  ('PROBLEM_REPORT', 'PRODUCTION', 'Report machine and material problems'),
  ('QUALITY_VIEW', 'QUALITY', 'View inspections and quality data'),
  ('QUALITY_INSPECT', 'QUALITY', 'Record inspections and measurements'),
  ('QUALITY_APPROVE', 'QUALITY', 'Approve batches and inspections'),
  ('QUALITY_REJECT', 'QUALITY', 'Reject batches and inspections'),
  ('QUALITY_HOLD', 'QUALITY', 'Place batches on hold'),
  ('SALES_VIEW', 'SALES', 'View sales orders and finished-goods availability'),
  ('SALES_CREATE', 'SALES', 'Create sales orders'),
  ('SALES_UPDATE', 'SALES', 'Update sales orders'),
  ('RESERVE_FG', 'SALES', 'Reserve finished goods'),
  ('DISPATCH_REQUEST', 'SALES', 'Create dispatch requests'),
  ('DISPATCH_VIEW', 'SALES', 'View dispatches'),
  ('DISPATCH_CREATE', 'SALES', 'Create dispatches'),
  ('DISPATCH_APPROVE', 'SALES', 'Approve dispatches'),
  ('MAINTENANCE_VIEW', 'MAINTENANCE', 'View machine status and maintenance history'),
  ('MAINTENANCE_MANAGE', 'MAINTENANCE', 'Manage maintenance requests and schedules'),
  ('REPORT_VIEW', 'INSIGHT', 'View reports'),
  ('DASHBOARD_VIEW', 'INSIGHT', 'View dashboards'),
  ('TRACEABILITY_VIEW', 'INSIGHT', 'View traceability'),
  ('EXPORT_DATA', 'INSIGHT', 'Export report and list data');

INSERT INTO roles (code, name, description, system_role) VALUES
  ('ADMIN', 'Administrator', 'Manages users, roles, configuration and master data; authorises large stock adjustments; reads everything', TRUE),
  ('ENGINEER', 'Engineer', 'Maintains spring products, specifications, BOMs and routings', TRUE),
  ('PRODUCTION_MANAGER', 'Production Manager', 'Plans, releases and closes production orders', TRUE),
  ('SUPERVISOR', 'Supervisor', 'Runs assigned production orders on the shop floor', TRUE),
  ('OPERATOR', 'Operator', 'Executes assigned operations and records output', TRUE),
  ('QUALITY_MANAGER', 'Quality Engineer / Manager', 'Inspects and approves, rejects or holds batches', TRUE),
  ('STORE_MANAGER', 'Inventory / Store Manager', 'Receives, issues, transfers and counts stock; requests adjustments', TRUE),
  ('PURCHASE_MANAGER', 'Purchase Manager', 'Manages suppliers, requisitions and purchase orders', TRUE),
  ('SALES', 'Sales / Customer Service', 'Manages customers, sales orders, reservations and dispatch requests', TRUE),
  ('DISPATCH', 'Dispatch / Logistics', 'Creates dispatches against approved sales orders', TRUE),
  ('MAINTENANCE', 'Maintenance Engineer', 'Maintains machines and records downtime', TRUE),
  ('STORE_OPERATOR', 'Store Operator', 'Warehouse-scoped receiving, issuing, transfers and counting', TRUE),
  ('MANAGEMENT', 'Management', 'Read-only dashboards and reports', TRUE);

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM (VALUES
  ('ADMIN', 'USER_CREATE'),
  ('ADMIN', 'USER_UPDATE'),
  ('ADMIN', 'USER_DELETE'),
  ('ADMIN', 'ROLE_MANAGE'),
  ('ADMIN', 'PERMISSION_MANAGE'),
  ('ADMIN', 'SETTINGS_MANAGE'),
  ('ADMIN', 'MASTERDATA_MANAGE'),
  ('ADMIN', 'SUPPLIER_MANAGE'),
  ('ADMIN', 'CUSTOMER_MANAGE'),
  ('ADMIN', 'WAREHOUSE_MANAGE'),
  ('ADMIN', 'LOCATION_MANAGE'),
  ('ADMIN', 'MACHINE_MANAGE'),
  ('ADMIN', 'OPERATION_MANAGE'),
  ('ADMIN', 'REJECTION_REASON_MANAGE'),
  ('ADMIN', 'INVENTORY_ADJUST'),
  ('ADMIN', 'ADJUST_APPROVE'),
  ('ADMIN', 'ADJUST_APPROVE_ADMIN'),
  ('ADMIN', 'PURCHASE_APPROVE'),
  ('ADMIN', 'DISPATCH_APPROVE'),
  ('ADMIN', 'EXPORT_DATA'),
  ('ADMIN', 'USER_VIEW'),
  ('ADMIN', 'AUDIT_VIEW'),
  ('ADMIN', 'MATERIAL_VIEW'),
  ('ADMIN', 'PRODUCT_VIEW'),
  ('ADMIN', 'BOM_VIEW'),
  ('ADMIN', 'INVENTORY_VIEW'),
  ('ADMIN', 'INVENTORY_VIEW_ALL'),
  ('ADMIN', 'VALUATION_VIEW'),
  ('ADMIN', 'PURCHASE_VIEW'),
  ('ADMIN', 'PRODUCTION_VIEW'),
  ('ADMIN', 'QUALITY_VIEW'),
  ('ADMIN', 'SALES_VIEW'),
  ('ADMIN', 'DISPATCH_VIEW'),
  ('ADMIN', 'MAINTENANCE_VIEW'),
  ('ADMIN', 'REPORT_VIEW'),
  ('ADMIN', 'DASHBOARD_VIEW'),
  ('ADMIN', 'TRACEABILITY_VIEW'),
  ('ENGINEER', 'PRODUCT_CREATE'),
  ('ENGINEER', 'PRODUCT_UPDATE'),
  ('ENGINEER', 'PRODUCT_VIEW'),
  ('ENGINEER', 'BOM_CREATE'),
  ('ENGINEER', 'BOM_UPDATE'),
  ('ENGINEER', 'BOM_REVIEW'),
  ('ENGINEER', 'BOM_APPROVE'),
  ('ENGINEER', 'BOM_VIEW'),
  ('ENGINEER', 'ROUTING_MANAGE'),
  ('ENGINEER', 'DRAWING_MANAGE'),
  ('ENGINEER', 'INVENTORY_VIEW'),
  ('ENGINEER', 'INVENTORY_VIEW_ALL'),
  ('ENGINEER', 'MATERIAL_VIEW'),
  ('ENGINEER', 'REPORT_VIEW'),
  ('PRODUCTION_MANAGER', 'PRODUCTION_CREATE'),
  ('PRODUCTION_MANAGER', 'PRODUCTION_UPDATE'),
  ('PRODUCTION_MANAGER', 'PRODUCTION_APPROVE'),
  ('PRODUCTION_MANAGER', 'PRODUCTION_RELEASE'),
  ('PRODUCTION_MANAGER', 'PRODUCTION_CLOSE'),
  ('PRODUCTION_MANAGER', 'PRODUCTION_REOPEN'),
  ('PRODUCTION_MANAGER', 'PRODUCTION_SCHEDULE'),
  ('PRODUCTION_MANAGER', 'PRODUCTION_ASSIGN'),
  ('PRODUCTION_MANAGER', 'PRODUCTION_VIEW'),
  ('PRODUCTION_MANAGER', 'INVENTORY_VIEW'),
  ('PRODUCTION_MANAGER', 'INVENTORY_VIEW_ALL'),
  ('PRODUCTION_MANAGER', 'REPORT_VIEW'),
  ('PRODUCTION_MANAGER', 'PRODUCT_VIEW'),
  ('PRODUCTION_MANAGER', 'BOM_VIEW'),
  ('PRODUCTION_MANAGER', 'MATERIAL_VIEW'),
  ('SUPERVISOR', 'PRODUCTION_EXECUTE'),
  ('SUPERVISOR', 'PRODUCTION_ASSIGN'),
  ('SUPERVISOR', 'DOWNTIME_RECORD'),
  ('SUPERVISOR', 'MATERIAL_REQUEST'),
  ('SUPERVISOR', 'PROBLEM_REPORT'),
  ('SUPERVISOR', 'PRODUCT_VIEW'),
  ('SUPERVISOR', 'ADJUST_REVIEW'),
  ('OPERATOR', 'PRODUCTION_EXECUTE'),
  ('OPERATOR', 'PROBLEM_REPORT'),
  ('QUALITY_MANAGER', 'QUALITY_INSPECT'),
  ('QUALITY_MANAGER', 'QUALITY_APPROVE'),
  ('QUALITY_MANAGER', 'QUALITY_REJECT'),
  ('QUALITY_MANAGER', 'QUALITY_HOLD'),
  ('QUALITY_MANAGER', 'QUALITY_VIEW'),
  ('QUALITY_MANAGER', 'REJECTION_REASON_MANAGE'),
  ('QUALITY_MANAGER', 'REPORT_VIEW'),
  ('QUALITY_MANAGER', 'TRACEABILITY_VIEW'),
  ('QUALITY_MANAGER', 'MATERIAL_VIEW'),
  ('QUALITY_MANAGER', 'PRODUCT_VIEW'),
  ('STORE_MANAGER', 'INVENTORY_VIEW'),
  ('STORE_MANAGER', 'INVENTORY_VIEW_ALL'),
  ('STORE_MANAGER', 'INVENTORY_RECEIVE'),
  ('STORE_MANAGER', 'INVENTORY_ISSUE'),
  ('STORE_MANAGER', 'INVENTORY_TRANSFER'),
  ('STORE_MANAGER', 'INVENTORY_RETURN'),
  ('STORE_MANAGER', 'STOCK_COUNT'),
  ('STORE_MANAGER', 'INVENTORY_ADJUST'),
  ('STORE_MANAGER', 'ADJUST_APPROVE'),
  ('STORE_MANAGER', 'LOCATION_MANAGE'),
  ('STORE_MANAGER', 'VALUATION_VIEW'),
  ('STORE_MANAGER', 'REPORT_VIEW'),
  ('STORE_MANAGER', 'MATERIAL_VIEW'),
  ('PURCHASE_MANAGER', 'PURCHASE_CREATE'),
  ('PURCHASE_MANAGER', 'PURCHASE_VIEW'),
  ('PURCHASE_MANAGER', 'REQUISITION_CREATE'),
  ('PURCHASE_MANAGER', 'SUPPLIER_MANAGE'),
  ('PURCHASE_MANAGER', 'MATERIAL_VIEW'),
  ('SALES', 'SALES_CREATE'),
  ('SALES', 'SALES_UPDATE'),
  ('SALES', 'SALES_VIEW'),
  ('SALES', 'CUSTOMER_MANAGE'),
  ('SALES', 'RESERVE_FG'),
  ('SALES', 'DISPATCH_REQUEST'),
  ('SALES', 'DISPATCH_VIEW'),
  ('SALES', 'PRODUCT_VIEW'),
  ('DISPATCH', 'DISPATCH_CREATE'),
  ('DISPATCH', 'DISPATCH_VIEW'),
  ('DISPATCH', 'SALES_VIEW'),
  ('DISPATCH', 'INVENTORY_VIEW'),
  ('DISPATCH', 'INVENTORY_VIEW_ALL'),
  ('MAINTENANCE', 'MACHINE_MANAGE'),
  ('MAINTENANCE', 'MAINTENANCE_MANAGE'),
  ('MAINTENANCE', 'MAINTENANCE_VIEW'),
  ('MAINTENANCE', 'DOWNTIME_RECORD'),
  ('STORE_OPERATOR', 'INVENTORY_VIEW'),
  ('STORE_OPERATOR', 'INVENTORY_RECEIVE'),
  ('STORE_OPERATOR', 'INVENTORY_ISSUE'),
  ('STORE_OPERATOR', 'INVENTORY_TRANSFER'),
  ('STORE_OPERATOR', 'INVENTORY_RETURN'),
  ('STORE_OPERATOR', 'STOCK_COUNT'),
  ('MANAGEMENT', 'MATERIAL_VIEW'),
  ('MANAGEMENT', 'PRODUCT_VIEW'),
  ('MANAGEMENT', 'BOM_VIEW'),
  ('MANAGEMENT', 'INVENTORY_VIEW'),
  ('MANAGEMENT', 'INVENTORY_VIEW_ALL'),
  ('MANAGEMENT', 'VALUATION_VIEW'),
  ('MANAGEMENT', 'PURCHASE_VIEW'),
  ('MANAGEMENT', 'PRODUCTION_VIEW'),
  ('MANAGEMENT', 'QUALITY_VIEW'),
  ('MANAGEMENT', 'SALES_VIEW'),
  ('MANAGEMENT', 'DISPATCH_VIEW'),
  ('MANAGEMENT', 'MAINTENANCE_VIEW'),
  ('MANAGEMENT', 'REPORT_VIEW'),
  ('MANAGEMENT', 'DASHBOARD_VIEW'),
  ('MANAGEMENT', 'TRACEABILITY_VIEW'),
  ('MANAGEMENT', 'EXPORT_DATA')
) AS m(role_code, permission_code)
JOIN roles r ON r.code = m.role_code
JOIN permissions p ON p.code = m.permission_code;

INSERT INTO rejection_reasons (reason_code, name, applies_to) VALUES
  ('DIMENSION', 'Incorrect Dimension', 'ALL'),
  ('WIRE_DIAMETER', 'Wrong Wire Diameter', 'ALL'),
  ('SURFACE_DEFECT', 'Surface Defect', 'ALL'),
  ('CRACK', 'Crack', 'ALL'),
  ('SPRING_RATE', 'Incorrect Spring Rate', 'FINAL'),
  ('HEAT_TREATMENT', 'Heat Treatment Failure', 'PROCESS'),
  ('COILING_DEFECT', 'Coiling Defect', 'PROCESS'),
  ('GRINDING_DEFECT', 'Grinding Defect', 'PROCESS'),
  ('CUSTOMER_SPEC', 'Customer Specification Failure', 'FINAL');

INSERT INTO operations (operation_code, name, default_machine_type, is_inspection) VALUES
  ('WIRE_DRAWING', 'Wire Drawing', 'WIRE_DRAWING', FALSE),
  ('COILING', 'Coiling', 'COILING', FALSE),
  ('CUTTING', 'Cutting', 'CUTTING', FALSE),
  ('GRINDING', 'Grinding', 'GRINDING', FALSE),
  ('HEAT_TREATMENT', 'Heat Treatment', 'FURNACE', FALSE),
  ('SHOT_PEENING', 'Shot Peening', 'SHOT_PEENING', FALSE),
  ('SURFACE_TREATMENT', 'Surface Treatment', 'SURFACE_TREATMENT', FALSE),
  ('INSPECTION', 'Inspection', 'INSPECTION', TRUE),
  ('PACKAGING', 'Packaging', 'PACKAGING', FALSE);

INSERT INTO system_settings (key, value, value_type, description) VALUES
  ('inventory.allow_negative_stock', 'false', 'BOOLEAN', 'Allow stock to go negative (Admin only; business rule 1)'),
  ('inventory.adjustment.admin_threshold', '10000.00', 'DECIMAL', 'Variance value (INR) above which a stock adjustment needs Admin approval'),
  ('inventory.costing.method', 'MOVING_AVERAGE', 'STRING', 'Inventory costing method'),
  ('inventory.aging_days', '180', 'INTEGER', 'Days in stock before an aging alert'),
  ('inventory.expiry_warning_days', '30', 'INTEGER', 'Days before expiry to raise an alert'),
  ('purchase.over_receipt_pct', '5', 'DECIMAL', 'Over-receipt tolerance on purchase orders (%)'),
  ('production.release.require_material', 'false', 'BOOLEAN', 'Block production release when material is short'),
  ('production.issue.tolerance_pct', '5', 'DECIMAL', 'Over-issue tolerance against the BOM (%)'),
  ('production.auto_backflush', 'true', 'BOOLEAN', 'Create MATERIAL_CONSUMPTION automatically from production output'),
  ('production.monthly_target', '0', 'INTEGER', 'Monthly production target shown on the dashboard'),
  ('quality.pending_hours', '24', 'INTEGER', 'Hours a pending inspection may wait before an alert'),
  ('quality.trace_granularity', 'ORDER', 'STRING', 'Traceability granularity: ORDER or BATCH'),
  ('sales.reservation.max_days', '14', 'INTEGER', 'Days before a stale FG reservation is released automatically'),
  ('security.password.min_length', '12', 'INTEGER', 'Minimum password length'),
  ('security.lockout.attempts', '5', 'INTEGER', 'Failed logins before the account is locked'),
  ('security.lockout.minutes', '15', 'INTEGER', 'Account lockout duration in minutes');
